honeynet/droidbot

com/dtmilano/android/viewclient.py, droidbot/droidbot.py
I don't know if this is a good fix. But I think your and my fix does the same, it sets 
```
if serialno is None:
serialno = '.*'
```
The advantage of my workaround is, that we does not change the external code. If we want to update the external code, it would be easier. Perhaps there is also another way, then copying the external code into the droidbot repository.
=> Workaround for #3

droidbot/types.py
In the past self.type was renamed to self.is_emulator.
Nothing big.
=> Fix old rename also in comments

droidbot/app_event.py, droidbot/state_transition_graph.py
States in UTG were mixed because of not using sorting. Besides they were shifted because the second state (after KeyEvent "Home") was not considered.
One more slight change: removed an unused variable in UtgDynamicFactory.
=> Fixes in UTG generation

droidbot/app.py, droidbot/app_event.py, droidbot/device.py
I've faced the same problem with processing viewclient structures (that they can return None in unexpected places).
Another problem was in saving profiler info on old Android versions (specifically Android 4.1.2 which is the only one working with droidbox). There is no --sampling key in am commands until Android 5.0 and we should use command without it otherwise the profiler does not start. Without sampling profiler traces get quite large and so we face another problem with obtaining them after 'am profile stop'. This command seems to be asyncronous and if we pull the profiler trace file from device immediately after 'am profile stop' we get it empty. I did not find a proper solution for this and put a sleep for 3 seconds here which is enough at least on my machine.
=> Fixes in processing viewclient structures and profiling events on old Android versions

droidbot/app_event.py
The sampling parameter in the call to adb shell wasn't converted to type 'str', causing program crashes. This PR fixed that.
=> fix sampling type error

droidbot/app_event.py, droidbot/droidbot.py, droidbot/start.py
This PR is to enable full method trace option (not sampling) on high Android versions (>=5.0).
Now the `-enable_method_profiling` option can be either
1. An integer indicating the sampling rate;
2. "full", indicating full method trace;
3. Not given, indicating method trace is disabled.
=> add full method trace for Android version >= 5.0

droidbot/app_event.py, droidbot/droidbot.py, droidbot/start.py
Add "bfs_no_shuffle" and "dfs_no_shuffle" to allow users to switch off the random.shuffle for views. This may be necessary for DroidBot to generate the same test sequences for multiple runs of a single app.
=> add no view shuffle option for bfs and dfs policy

droidbot/device.py, droidbot/droidbot.py, droidbot/start.py
Users can choose to grant all permissions silently when testing apps on Android versions higher than Marshmallow by using `-grant_perm` option.
This eliminates redundant permission confirm pop-up windows when there is no need.
=> add grant permission option

droidbot/app_event.py
the `state_transition_graph.py` module is lack of maintenance and needs refactoring.
This PR eliminates the use of it temporarily.
=> eliminate buggy utg builder

droidbot/app_event.py
Fix the bug that script for an state could work only once.
In the origin code, `self.script_events` are shallow copied from `operation.events`, and they're poped while being executed, causing elimination to the `operation.events`.
This PR fixed this by using index `self.script_event_idx` to access scripted events.
=> fix script operation copy

droidbot/device.py, droidbot/device_state.py, droidbot/droidbot.py, droidbot/start.py, droidbot/utg.py
Currently the minicap support in DroidBot has the following
two problems:
1) Minicap will save screenshots in JPEG format, which is
now unhandled by DroidBot;
2) Minicap officially doesn't support emulators, causing
black blank screenshot on emulators.
This PR should fix the problems by
1) Use JPEG format when Minicap is enabled;
2) Disable Minicap when emulator is given by is_emulator
option.
=> minicap: fix minicap support problems

droidbot/input_manager.py, droidbot/input_policy.py, droidbot/start.py
This commit
1) merges the old bfs/dfs policy into UtgNaiveSearchPolicy;
2) merges the new bfs/dfs policy into UtgGreedySearchPolicy,
which needs further implementation and optimization;
3) fixes a bug in UtgNaiveSearchPolicy not using self.current_state
to update UTG;
4) adds a warning when no valid input policy is chosen.
=> input_policy: refactor and bug fix

droidbot/adapter/droidbot_app.py, droidbot/adapter/minicap.py
Those calls might cause deadlocks, it is not recommended to use them. See the note for subprocess.check_call in https://docs.python.org/2/library/subprocess.html
I faced such deadlocks in the old version of droidbot at the point of installing the application (in device.py). I see that in the currrent version it was substituted by subprocess.Popen but the other parts  of droidbot still use these buggy calls.
=> Get rid of subprocess.call subprocess.check_call with subprocess.PIPE parameters

droidbot/adapter/adb.py, droidbot/adapter/droidbot_app.py, droidbot/device.py, droidbot/droidbot.py, droidbot/start.py
Here are some fixes for automatically enabling droidbot accessibility service. The first and the second commit work for older Android that already has command `adb shell settings ...` The command for enabling accessibility in general was missed.
And the third commit is for Android that uses settings.db to store such settings (API level < 23).  However, it requires device restart so I've added an option -accessibility_auto to use this type of enabling. By default the user is required to enable the accessibility service manually.
=> Enabling accessibility service automatically for old Android

README.md, droidbot/__init__.py, droidbot/adapter/adb.py, droidbot/adapter/droidbot_app.py, droidbot/adapter/droidbot_ime.py, droidbot/adapter/jdwp.py, droidbot/adapter/logcat.py, droidbot/adapter/minicap.py, droidbot/adapter/process_monitor.py, droidbot/adapter/telnet.py, droidbot/adapter/user_input_monitor.py, droidbot/app.py, droidbot/device.py, droidbot/device_state.py, droidbot/droidbot.py, droidbot/env_manager.py, droidbot/input_event.py, droidbot/input_manager.py, droidbot/input_policy.py, droidbot/input_script.py, droidbot/start.py, droidbot/utg.py, droidbot/utils.py, setup.py
This PR makes DroidBot compatible with Python3. The main changes:
- update to the last version of [androguard](https://github.com/androguard/androguard) (which has to be installed directly from GitHub as the version installed with `pip` seems not working in Python3, that's why you now need to install DroidBot using the `--process-dependency-links` flag)
- update `print` statements and some checks regarding strings
- update imports
This is still a work in progress, as I wold like to add more:
- change all `print` statements into `logger.something`
- use `.format(...)` instead of `%` in strings
=> Add Python3 compatibility

droidbot/start.py
Greedy DFS policy was sent twice instead of Greedy BFS in the final case
=> Small error in policy name

droidbot/adapter/logcat.py
Fixed the below exception( Tested in python 3 environment windows)
Exception in thread Thread-5:
Traceback (most recent call last):
File "...lib\threading.py", line 917, in _bootstrap_inner
self.run()
File "...lib\threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "...droidbot\adapter\logcat.py", line 61, in handle_output
f.write(line)
File "...lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uff1a' in position 53: character maps to <undefined>
=> Fixed UnicodeEncodeError 'charmap' codec can't encode character error

droidbot/adapter/adb.py
Activity names containing the `$` character are not escaped, causing the shell to evaluate some parts of the argument string.
When providing an APK file with main activity such as `com.discord.app.AppActivity$Main`, an incorrect start intent for activity `com.discord.app.AppActivity` is made.
This change escapes arguments passed to `device.adb.shell()` and is compatible with Python 2 and Python 3.
=> Shell-escape arguments passed to adb shell

setup.py
Androguard 3.3.5 introduces a bug that causes activities to incorrectly return two dots when the `android:name` attribute of the `activity` element in the Android manifest contains a shorthand name (e.g. `.App` instead of `org.mozilla.firefox.App`).
This leads to the following error message when attempting to start the activity:
```
Error: Activity class {org.mozilla.firefox/org.mozilla.firefox..App} does not exist.
```
The issue has been fixed upstream by androguard/androguard@b184771eab85f73199355f287059c557c20da2d1
The latest release that includes this fix is version 3.4.0a1 which is marked as a pre-release.
This PR updates the Androguard dependency to include the fix.
=> Fix incorrect main activity for certain apps

droidbot/droidbot.py
When using timeouts, droidbot raises:
AttributeError: 'Timer' object has no attribute 'isAlive'
=> bugfix: replaced isAlive call for is_alive

droidbot/adapter/droidbot_ime.py, droidbot/device.py, droidbot/device_state.py
This PR closes issue #151.
1. Added a flag to check if the API Level is 32+ and disable Minicap
2. Updated regex match patterns to support changes in API Level 32+
*After the update, tested it on Google Pixel 3 (Android 9 / API Level 28) and Google Pixel 6a (Android 12L / API Level 32).
=> [Feature] Update Droidbot tool to support Android API Level 32
